plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

def lwjglVersion = '3.3.3'

def lwjglNatives = org.gradle.internal.os.OperatingSystem.current().isWindows() ? 'natives-windows' :
        (org.gradle.internal.os.OperatingSystem.current().isMacOsX() ? 'natives-macos' : 'natives-linux')

dependencies {
    implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")
    implementation 'org.lwjgl:lwjgl'
    implementation 'org.lwjgl:lwjgl-glfw'
    implementation 'org.lwjgl:lwjgl-opengl'
    implementation 'org.lwjgl:lwjgl-stb'
    implementation 'org.joml:joml:1.10.5'

    runtimeOnly "org.lwjgl:lwjgl::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-glfw::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-opengl::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-stb::$lwjglNatives"
}

application {
    mainClass = 'com.gamefps.Game'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}
